### ISSUE TITLE
Windows Wazuh Client info

### ISSUE THREAD

**Issue by CadieuxP** [citybasebrooks/SIAC#1]
Registering a wazuh agent on windows requires generation of an agent key. The documentation for this process is at:
https://documentation.wazuh.com/current/user-manual/registering/registration-process.html

There is an easy powershell script provided that works very well to register agents using the RESTful API. Be advised that you need to configure the script to point to your installation directory (on the local windows system) and configure the “Wazuh-Manager-IP” to the IP Address of your server.
https://raw.githubusercontent.com/wazuh/wazuh-api/3.2/examples/api-register-agent.ps1

**Comment by citybasebrooks** [comment]
Updated the docs.  Thank you, Pierre!
